x-common-variables: &common-variables
  MYSQL_HOST: mysql
  MYSQL_ROOT_PASSWORD: abcd
  MYSQL_USER: php_app
  MYSQL_PASSWORD: php_app
  MYSQL_DATABASE: php_app_development
  MYSQL_PORT: 3307

services:
  mysql:
    container_name: php_app-mysql
    image: mysql:8.4
    command: mysqld -h 127.0.0.1 -P 3306
    environment:
      <<: *common-variables
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql
    ports:
      - 3307:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "php_app",
          "--password=php_app",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: no
    stdin_open: true
    tty: true

  php_app:
    container_name: php_app
    hostname: php-app-host
    environment:
      <<: *common-variables
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/my-edited-php.ini
    command: php -S 0.0.0.0:3000 -t /var/www/html index.php
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mysql
    stdin_open: true
    tty: true

networks:
  mysql:

volumes:
  mysql-data:
