@startuml "Voting System Class Diagram"

class User {
  id : Integer <<PK>>
  name : String
  created_at : Datetime
  updated_at : Datetime
}

class Voting {
  id : Integer <<PK>>
  datetime_start : Datetime
  datetime_end : Datetime
  creator_id : Integer
  name : String
  description : Text
  created_at : Datetime
  updated_at : Datetime
}

class Question {
  id : Integer <<PK>>
  voting_id : Integer
  name : String
  description : Text
  created_at : Datetime
  updated_at : Datetime
}

enum VoteOption {
  YES
  NO
  ABSTAIN
}

class UsersQuestion {
  user_id : Integer <<PK>>
  question_id : Integer <<PK>>
  chosen_option : VoteOption
  created_at : Datetime
  updated_at : Datetime
}

' Vazby
Voting "1" -- "0..*" Question
User "1" -- "0..*" UsersQuestion
Question "1" -- "0..*" UsersQuestion
User "1" - "0..*" Voting

@enduml
