<?php

declare(strict_types=1);

namespace ActiveModel\Validations {
  if (!function_exists('ActiveModel\\Validations\\t')) {
    function t(string $key, array $params = []): string
    {
      return $key;
    }
  }
}

namespace {

  if (!function_exists('toSnakeCase')) {
    require_once __DIR__ . '/../../lib/Helpers.php';
  }
  if (!class_exists('Logger')) {
    require_once __DIR__ . '/../../lib/Logger.php';
  }
  if (!class_exists('Collection')) {
    require_once __DIR__ . '/../../lib/active_model/relations/Collection.php';
  }
  if (!class_exists('QueryBuilder')) {
    require_once __DIR__ . '/../../lib/active_model/relations/QueryBuilder.php';
  }
  if (!class_exists('Pagination')) {
    require_once __DIR__ . '/../../lib/active_model/relations/Pagination.php';
  }
  if (!trait_exists('Relations')) {
    require_once __DIR__ . '/../../lib/active_model/relations/Relations.php';
  }
  if (!trait_exists('Attributes')) {
    require_once __DIR__ . '/../../lib/active_model/attributes/Attributes.php';
  }
  if (!trait_exists('Validations')) {
    require_once __DIR__ . '/../../lib/active_model/validations/Validations.php';
  }
  if (!class_exists('ActiveModel')) {
    require_once __DIR__ . '/../../lib/active_model/ActiveModel.php';
  }
  if (!class_exists('Database')) {
    class Database
    {
      public function getConnection(): object
      {
        return new class {
          public function close(): void {}
        };
      }
    }
  }
  if (!class_exists('ApplicationRecord')) {
    require_once __DIR__ . '/../../app/models/ApplicationRecord.php';
  }
  foreach (['User', 'Post', 'Event', 'Comment', 'Attachment', 'Voting', 'Question', 'UsersQuestion'] as $_m) {
    $cls = $_m;
    if (!class_exists($cls)) {
      require_once __DIR__ . "/../../app/models/{$_m}.php";
    }
  }

  use PHPUnit\Framework\TestCase;

  /**
   * Tests for Attachment-specific behaviour that can be verified without a DB.
   */
  final class AttachmentTest extends TestCase
  {
    // ---- Token auto-generation ----

    public function testTokenIsAutoGeneratedWhenNotSupplied(): void
    {
      $a = new Attachment([]);
      $this->assertNotNull($a->token);
      $this->assertIsString($a->token);
    }

    public function testAutoGeneratedTokenIsHexString(): void
    {
      $a = new Attachment([]);
      $this->assertMatchesRegularExpression('/^[0-9a-f]+$/', $a->token);
    }

    public function testAutoGeneratedTokenIsThirtyTwoCharacters(): void
    {
      // bin2hex(random_bytes(16)) produces 32 hex characters
      $a = new Attachment([]);
      $this->assertSame(32, strlen($a->token));
    }

    public function testTokenIsNotOverwrittenWhenSupplied(): void
    {
      $a = new Attachment(['token' => 'mypresettoken']);
      $this->assertSame('mypresettoken', $a->token);
    }

    public function testEachInstanceGetsUniqueToken(): void
    {
      $tokens = [];
      for ($i = 0; $i < 10; $i++) {
        $tokens[] = (new Attachment([]))->token;
      }
      $this->assertCount(10, array_unique($tokens));
    }

    // ---- Attachment static declarations ----

    public function testAttachmentDbAttributesContainsExpectedColumns(): void
    {
      $ref = new ReflectionProperty('Attachment', 'db_attributes');
      $ref->setAccessible(true);
      $attrs = $ref->getValue();
      foreach (['id', 'resource_id', 'resource_type', 'file_name', 'file_size', 'file_type', 'visible_name', 'token', 'creator_id', 'is_publicly_visible'] as $col) {
        $this->assertContains($col, $attrs, "Attachment::\$db_attributes missing '$col'");
      }
    }

    public function testAttachmentValidatesPresenceOfRequiredFields(): void
    {
      $ref = new ReflectionProperty('Attachment', 'validations');
      $ref->setAccessible(true);
      $v = $ref->getValue();
      foreach (['creator_id', 'file_name', 'file_size', 'file_type', 'token', 'resource_id', 'resource_type', 'visible_name'] as $f) {
        $this->assertContains($f, $v['presence'], "Attachment validation missing presence for '$f'");
      }
    }
  }
}
